#!/bin/sh

# Preset to disable autodetect:
#export MAKE=nmake
#export MAKE=gnumake


runner=_engine/run_case

if [ "$*" == "" ]; then
#22 <-	find -name '*.case' -not -path "./_*/*" -exec ${runner} \{\} \;
	find -name '*.case' -not -path "./_*/*" -print0 | xargs -0 -n1 ${runner}
else
	for c in "$*"; do 
		${runner} "$c"
	done
fi
